### ISSUE TITLE
Feature request - export of data

### ISSUE THREAD

**Issue by Hipapheralkus** [tan-yaka/burp-timer#2]
Hi, 
I think this extender is very good, and I want to ask if it would be possible to extend the functionality, so that table could be exported - especially request & time it took. This is very good extender to check for performance issues, but afterwards it is hard to report them once they arise in higher numbers.

**Comment by tan-yaka** [comment]
Hi, thanks for the feedback, I'm glad you are finding it useful. Not sure if or when I will implement this feature but as a work around you can ctrl-a in the table to highlight all rows, then ctrl-c to copy and then paste into a spreadsheet. Just tried it with LibreOffice and it works well, all the columns are preserved.

**Comment by Hipapheralkus** [comment]
awesome, thanks:)
