### ISSUE TITLE
Feature request - Time of request in separate column

### ISSUE THREAD

**Issue by Hipapheralkus** [tan-yaka/burp-timer#3]
For reporting of potential performance problems, and connecting them to CPU spikes from server logs, it would be very good to have special column with timestamp when that request was fired.

**Comment by tan-yaka** [comment]
Thanks for the request, I have added a column 'Timestamp' of the form '2017-10-17T10:25:11.745'. Will have to wait for Portswigger to update the extension in the Bapp store, it will be version 1.0.1
