### ISSUE TITLE
Incorporate Extender to tools

### ISSUE THREAD

**Issue by Hipapheralkus** [tan-yaka/burp-timer#4]
Hi,
We have an extender which is having specific payloads and checks for certain vulnerabilities. However, I don't see the traffic flowing through Request Timer, although I have all the tools selected. Would it be possible to incorporate requests made by Extenders as well?

**Comment by tan-yaka** [comment]
Hi, I've just checked and requests originating from an extension do show up as 'Extender' in the tool column with 'All' selected. I'm not sure if any more detail can be obtained about the extension that made the request though, looking at the Burp API I suspect not.

**Comment by Hipapheralkus** [comment]
Upon further inspecting results, I think that another issue #5 could have been responsible for my confusion, because I didn't see payloads which I was expecting to come from our internally developed extender with specific payloads. I will have a second look when issue #5 is fixed, thank you

**Comment by Hipapheralkus** [comment]
as I though, fix for #5 helped and this is no longer an issue. My bad, sorry for that:)
